### ISSUE TITLE
Recreate Dashboard - Climate and Weather

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#11]
- [x] Chart 1: Annual mean temperature (°C) for the UK, 1884 to 2020
- [x] Chart 2: Mean annual rainfall (mm) UK, 1862 to 2020
- [x] Chart 3: UK growing season length in days, 1960 to 2020
- [x] Chart 4: Annual mean temperature (°C) for the UK, England, Scotland, Wales and Northern Ireland, 1884 to 2020
- [x] Text and link to Met Office website

**Comment by osamede20** [comment]
All four charts recreated, published and ready for review.
https://staging.climate-change.data.gov.uk/dashboards/climate-and-weather

**Comment by peterfrenchons** [comment]
Observations Chart 1:
2020 x axis label missing

**Comment by peterfrenchons** [comment]
@osamede20 . This is ready to go through following review/QA. Please ignore the "General Observations" section of my feedback at the moment. Thanks

**Comment by TahaRana97** [comment]
@osamede20 to update with comments
