### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#17]
Users to be interviewed re Climate portal v1.1 and v2.0. 
Feedback to be compiled, assessed and findings shared with relevant personnel.

Feedback will inform any changes needed to design and UX.

Action to take place over 2 sprints due to timing
- [x] Interviews complete
- [x] Feedback compiled - expected 01/08
- [x] Feedback shared
- [x] Next steps decided

**Comment by JohnLewisUR** [comment]
Thanks Peter. Do you want me to check off the boxes as we progress, or do you want me to leave that to you, so you can track progress, etc? Not ready to tick any just yet, but our last interview is today.
