### ISSUE TITLE
QA issues with Home page

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#21]
- [x] Beta banner - not at all obvious about the link to leave feedback. 
- [x] Feedback - need to link to mailto:support@...... like on current site. Currently the link shows the URL of the page
- [x] "New Article". This is not a new article. Can we put a more relevant label on it?
- [ ] DECISION POINT: Hide search function until defined what search results we want to return (e.g. try searching "Emissions"). NB - this search function can be sorted out after v.2.0 put live
- [x] Review title of drivers tile - current title not exactly what being shown?
- [x] Mitigation tile - correct spelling of "non-enewable" in legend
- [ ] Update dates on articles (currently all say 29 March)

**Comment by StRhys** [comment]
"New Article" has been fixed with [#620](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/620)

**Comment by StRhys** [comment]
Feedback link fixed in PR [#635](https://github.com/GSS-Cogs/dd-cms/pull/635)
