### ISSUE TITLE
IDS logo and "Powered by" statement in page footer

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#22]
As per current portal, with the addition of the new IDS logo

**Comment by JohnLewisUR** [comment]
Design have produced an option for this - for review

**Comment by gareth-lewis** [comment]
![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/059d7212-5d7c-4d75-8763-69021b71bf1b)

**Comment by JasonHowell** [comment]
Need to create card for the development.

**Comment by peterfrenchons** [comment]
@JasonHowell . Can this card be used for the dev? - seems to have the relevant stuff on it.
