### ISSUE TITLE
QA feedback for article "UK Climate is changing" #338

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#25]
Link to figure 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14 not in v2.0 but is it needed? I guess consistency of experience needed across all articles?

Figure 5 "Coal" and "Other Fossil" fuels totals have been combined on v2.0.  

In Adaptation section, "Woodlands" subheading is missing

"can sequester carbon at a higher rate than other semi-natural habitats" link goes to 404. Also issue on current live. Need to find right link?

"benefits from natural trees" link on v2.0 different from v1.1 but both links don't work.......

"UK covered by woodland" link different on v2.0 and goes to a 404 error. v1.1 is ok

Figure 8 - UK data series missing on v2.0 but in effect it is showing on hover text (NB - accessibility needs might mean hover text is not sufficient?)

Figure 12 - Y axis label truncated

Figure 13 -Different format of number v2.0 vs v1.1. Maybe tidy up by adding a thousands ',' to make it easier to read?

Figure 14 -  Different format of number v2.0 vs v1.1. Maybe tidy up by adding a thousands ',' to make it easier to read?

**Comment by becwilliams** [comment]
Outstanding issues:
- Adding links to figures is blocked by Issue #553
- Figure 8: UK total currently showing only when you hover over. Would like to include UK total as a separate line on the chart but currently no capability in CMS for a combo chart?
- Figures 13 & 14: cannot currently customise the hover over labels
