### ISSUE TITLE
QA for charts

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#27]
Feedback from CC team to be actioned:

- [x] Chart 4 on Emissions dashboard - this looks quite different to the CC1 version because we have included a bar for total GHG emissions, this bar makes the rest of the chart quite sparse and hard to read. Is there an easy way to remove the total from the chart (hoping you can just add a bit of code to the SPARQL)?

- [x] Chart 5 on Adaptation dashboard - this also looks quite different to that on CC1. I can’t figure out why we have more data points for Northern Ireland on CC2 than we do on the CC1 (i.e. the NI data starts from 2007/08 on CC1 but from 2005/06 on CC2, so this doesn’t match the footnote wording which says we only have data for all countries from 2007/08). Just wondering if you had any insight on this? I don’t know much about how this chart was built…Could it be something to do with the SPARQL/the way the 3-year average is being calculated?

**Comment by osamede20** [comment]
Chart 4 on Emissions board: the bar for total GHG emissions is removed.

Chart 5 on Adaptation dashboard: The existing SPARQL query did not capture the correct start dates for Northern Ireland.
A csv file is now used to update the chart. The SPARQL query could be created at a later time.
