### ISSUE TITLE
1 Update "Greenhouse gas emissions on a territorial, residence and carbon footprint basis: UK, 1990 to 2020 and provisional 2021 (Mt CO2e)" DB: EMISSIONS

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#33]
Linked to data transform #502

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [ ] Update SPARQL query
- [ ] QA done and signed off

NB - original chart is driven by CSV. Agreed to drive this update also by CSV with SPARQL query investigation after the launch under a new ticket.

**Comment by Shannon95** [comment]
After a discussion with Bec to clarify where the figures come from a CSV has been created with updated figures to represent the data within Emissions Fig 1. Please see the CSV created under Home/Dashboards/Emissions with the name `CSV - Greenhouse gas emissions on a territorial, residence and carbon footprint basis: UK, 1990 to 2020 and provisional 2021 (Mt CO2e) : 2022-10-26`

Or click [here](https://beta.climate-change.data.gov.uk/dashboards/emissions/csv-greenhouse-gas-emissions-on-a-territorial-residence-and-carbon-footprint-basis-uk-1990-to-2020-and-provisional-2021-mt-co2e.csv)


Attaching the csv for reference: 

[CSV Greenhouse gas emissions on a territorial, residence and carbon footprint basis- UK, 1990 to 2020 and provisional 2021 (Mt CO2e).csv](https://github.com/GSS-Cogs/ukstats.ccv2.theme/files/9868198/CSV.Greenhouse.gas.emissions.on.a.territorial.residence.and.carbon.footprint.basis-.UK.1990.to.2020.and.provisional.2021.Mt.CO2e.csv)
