### ISSUE TITLE
4 Primary energy demand, UK, 1995 to 2020, million tonnes of oil equivalent (Mtoe) DB: DRIVERS

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#36]
Linked to data #523

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [x] Update SPARQL query
- [ ] QA done and signed off

**Comment by Shannon95** [comment]
An updated SPARQL query using the new [dataset](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fbeis-energy-trends-table-1-2-extract-2021%2Finland-energy-consumption-primary-fuel-input-basis-2021%23dataset-catalog-entry&apply-filters=false&show-uris=false) has been created and loads in data as expected up to 2021. 

Please find the query created under Home/Dashboards/Drivers with the name **SPARQL - Primary energy demand, UK, 1995 to 2021, million tonnes of oil equivalent (Mtoe) : 2022-10-21** or click [here](https://beta.climate-change.data.gov.uk/dashboards/drivers/sparql-primary-energy-demand-uk-1995-to-2020-million-tonnes-of-oil-equivalent-mtoe-2022-10-21). 

I am attaching the actual query below for reference : 
```
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdmxd: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX data: <http://gss-data.org.uk/data/climate-change/beis-energy-trends-table-1-2-extract-2021/inland-energy-consumption-primary-fuel-input-basis-2021#>
PREFIX energy: <http://gss-data.org.uk/def/energy/property/dimension/>
PREFIX meas:<http://gss-data.org.uk/data/climate-change/beis-energy-trends-table-1-2-extract-2021/inland-energy-consumption-primary-fuel-input-basis-2021#measure/>
PREFIX fuel: <http://gss-data.org.uk/def/energy/concept/fuel/>

SELECT ?year ?fuelLabel ?measureType ?value
WHERE { 
	?obs qb:dataSet data:dataset ;
	energy:fuel ?fuel ;
	meas:energy-consumption ?value ;
	sdmxd:refPeriod [ rdfs:label ?year ] ;
	qb:measureType [ rdfs:label ?measureType ] ;

    FILTER(?fuel NOT IN (fuel:all,fuel:renewables,fuel:fossil-fuels))
	?fuel rdfs:label ?fuelLabel
}
ORDER BY ?year ?fuelLabel
```
