### ISSUE TITLE
7 Low-carbon energy consumption by fuel type, UK, 1995 to 2020, (million tonnes of oil equivalent) DB: MITIGATION

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#39]
Linked to data 523

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [x] Update SPARQL query
- [ ] QA done and signed off

**Comment by Shannon95** [comment]
An updated SPARQL query using the [new](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fbeis-energy-trends-table-1-2-extract-2021%2Finland-energy-consumption-primary-fuel-input-basis-2021%23dataset-catalog-entry&apply-filters=false&show-uris=false) dataset has been created and loads in data as expected up to 2021.

Please find the query created under Home/Dashboards/Mitigation with the name SPARQL - Low-carbon energy consumption by fuel type, UK, 1995 to 2021, (million tonnes of oil equivalent): 2022-10-21 : 2022-10-21 or click [here](https://beta.climate-change.data.gov.uk/dashboards/mitigation/sparql-low-carbon-energy-consumption-by-fuel-type-uk-1995-to-2021-million-tonnes-of-oil-equivalent-2022-10-21).

I am attaching the actual query below for reference :

```
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mes:<http://gss-data.org.uk/data/climate-change/beis-energy-trends-table-1-2-extract-2021/inland-energy-consumption-primary-fuel-input-basis-2021#measure/>
PREFIX dim: <http://gss-data.org.uk/def/energy/property/dimension/>
PREFIX sdmxd: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX dat: <http://gss-data.org.uk/data/climate-change/beis-energy-trends-table-1-2-extract-2021/inland-energy-consumption-primary-fuel-input-basis-2021#>
PREFIX cons:<http://gss-data.org.uk/def/energy/concept/fuel/>

SELECT  ?year ?fuel (xsd:float(?value) AS ?consumption)
WHERE { ?s qb:dataSet dat:dataset ;
           mes:energy-consumption ?value ;
           dim:fuel ?fuel_uri ;
           sdmxd:refPeriod ?year_uri .
       ?year_uri rdfs:label ?year .
       VALUES (?fuel_uri ?fuel) 
       {( cons:nuclear "Nuclear")
                (cons:bioenergy-and-waste "Bioenergy and waste")
        (cons:wind-solar-and-hydro "Wind, solar and hydro") }
      } 
ORDER BY ?year ?fuel

```
