### ISSUE TITLE
8 Area of woodland in the UK, million hectares, 1998 to 2021 DB: ADAPTATION

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#40]
Linked to data 533

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [x] Update SPARQL query
- [ ] QA done and signed off

**Comment by Shannon95** [comment]
An updated SPARQL query using the new dataset has been created and loads in data as expected up to 2022. 

This will allow for the chart (Adaption fig 2)  to be updated with the latest data source, which can be found here: 
[Forestry Statistics 2022 Woodland Area](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fforestry-research-forestry-statistics-2022-woodland-area%2Fforestry-statistics-2022-woodland-area%23dataset-catalog-entry)

Please find the query created under Home/Dashboards/Adaptation with the name `Sparql - Area of woodland in the UK, million hectares, 1998 to 2022: 2022-10-24` or click [here](https://beta.climate-change.data.gov.uk/dashboards/adaptation/sparql-area-of-woodland-in-the-uk-million-hectares-1998-to-2022-2022-10-24).

I am attaching the actual sparql query below for reference :

```
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX data: <http://gss-data.org.uk/data/climate-change/forestry-research-forestry-statistics-2022-woodland-area/forestry-statistics-2022-woodland-area#>
PREFIX meas: <http://gss-data.org.uk/def/climate-change/measure/>
PREFIX dim:<http://gss-data.org.uk/data/climate-change/forestry-research-forestry-statistics-2022-woodland-area/forestry-statistics-2022-woodland-area#dimension/>

SELECT  ?woodland ?country ?year
WHERE { ?s qb:dataSet data:dataset ;
		   meas:woodland ?woodland ;
		   dim:country [ rdfs:label ?country ] ;
		   dim:year [ rdfs:label ?year ] ;
 }
ORDER BY ?year ?woodland
```
