### ISSUE TITLE
9 New planting of UK woodlands, thousand hectares, 1976 to 2021 DB: ADAPTATION

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#41]
Linked to data 530

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [x] Update SPARQL query
- [ ] QA done and signed off

**Comment by Shannon95** [comment]
An updated SPARQL query using the new dataset has been created and loads in data as expected up to 2022.

This will allow for the chart (Adaption fig 3) to be updated with the latest data source, which can be found here:
[Forestry Statistics 2022 New Planting](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fforestry-research-forestry-statistics-2022-new-planting%2Fforestry-statistics-2022-new-planting%23dataset-catalog-entry)

Please find the query created under Home/Dashboards/Adaptation with the name `Sparql - New planting of UK woodlands, thousand hectares, 1976 to 2022 : 2022-10-24` or click [here](https://beta.climate-change.data.gov.uk/dashboards/adaptation/sparql-new-planting-of-uk-woodlands-thousand-hectares-1976-to-2022-2022-10-24).

I am attaching the actual sparql query below for reference :
```

PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX scovo: <http://purl.org/NET/scovo#>
PREFIX sdmxa: <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX meas: <http://gss-data.org.uk/def/climate-change/measure/>
PREFIX data: <http://gss-data.org.uk/data/climate-change/forestry-research-forestry-statistics-2022-new-planting/forestry-statistics-2022-new-planting#>
PREFIX dim: <http://gss-data.org.uk/data/climate-change/forestry-research-forestry-statistics-2022-new-planting/forestry-statistics-2022-new-planting#dimension/>
PREFIX def: <http://gss-data.org.uk/def/climate-change/property/dimension/>

 SELECT * {
                {
                    SELECT ?year ?type ?value
                        WHERE {
                            ?obs qb:dataSet data:dataset ;
                                dim:year [ rdfs:label ?year ] ;
                                qb:measureType [ rdfs:label ?type ] ;
                                meas:new-broadleaves ?value;
                        }
                }
                UNION
                {
                        SELECT ?year ?type ?value
                            WHERE {
                                ?obs qb:dataSet data:dataset ;
                                    dim:year [ rdfs:label ?year ] ;
                                    qb:measureType [ rdfs:label ?type ] ;
                                    meas:new-conifers ?value;
                            }
                }
            }
            ORDER BY ?year ?type
```
