### ISSUE TITLE
Check SPARQL queries for EPC on Mitigation dashboard

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#64]
Report from Bec that SPARQL queries need updating following recent update of datasets. 
Could we check these please and update as necessary.
Thanks

**Comment by Shannon95** [comment]
Both Figures 4 and 5 on the Mitigation dashboard needed new sparql queries created to point / wrangle the new data which previously was a bespoke csv file loaded onto pmd Beta. 

Mitigation fig 4's new sparql query can be found under Home/Dashboards/Mitigation with the name `SPARQL - Number of records added to register for existing homes energy efficiency rating, 2009 to 2021, England and Wales: 2022-10-26` or click [here](https://beta.climate-change.data.gov.uk/dashboards/mitigation/sparql-number-of-records-added-to-register-for-existing-homes-energy-efficiency-rating-2009-to-2021-england-and-wales-2022-10-26).  
The updated source for this data is : [Domestic Energy Performance Certificates for existing dwellings by energy efficiency rating
 ](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fmhclg-table-eb1-domestic-energy-performance-certificates-for-existing-dwellings-by-energy-efficiency-rating%2Fdomestic-energy-performance-certificates-for-existing-dwellings-by-energy-efficiency-rating.csv%23dataset-catalog-entry)


Mitigation fig 5's new sparql query can be found under Home/Dashboards/Mitigation with the nameSPARQL - Number of records added to register for new homes energy efficiency rating, 2009 to 2021, England and Wales — Energy efficiency of domestic buildings: 2022-10-26 or click [here](https://beta.climate-change.data.gov.uk/dashboards/mitigation/sparql-number-of-records-added-to-register-for-new-homes-energy-efficiency-rating-2009-to-2021-england-and-wales-2014-energy-efficiency-of-domestic-buildings-2022-10-26). 
The updated source for this data is: [Domestic Energy Performance Certificates for new dwellings by energy efficiency rating](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fmhclg-table-nb1-domestic-energy-performance-certificates-for-new-dwellings-by-energy-efficiency-rating%2Fdomestic-energy-performance-certificates-for-new-dwellings-by-energy-efficiency-rating.csv%23dataset-catalog-entry)


Note both now include the Efficiency Efficiency Rating of 'Not Recorded' this was previously not used within the charts. I can remove it from the query if need be but I believe you can just not select it as part of the graph.
