### ISSUE TITLE
10 UK water leakage, average megalitres per day, 2002-03 to 2019-20 DB: ADAPTATION

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#69]
Linked to ticket #42

Needs the way figures are calculated to be checked as well as updated to included latest data on PMD. Question marks over the original chart and figures used.

- [ ] Check and update title
- [ ] Check and update summary
- [ ] Check and update footnotes
- [ ] Update source link
- [ ] Update SPARQL query
- [ ] QA done and signed off

**Comment by peterfrenchons** [comment]
Discussion with CC team on need of SPARQL vs the CSV used with discrepancies

**Comment by peterfrenchons** [comment]
Is this still relevant?

**Comment by osamede20** [comment]
No, it is no longer relevant; the dataset has been updated
