### ISSUE TITLE
Update of GeoJson on PMD

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#70]
Needed to support geographic representation due to changes in Northamptonshire in 2021.
Swirrl updating and expected to be available around the end of the sprint

**Comment by charlesons** [comment]
This has been tested in issue https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/dd-cms/738

**Comment by osamede20** [comment]
The Emissions maps are rendering correctly with the updated GeoJSON boundaries data on PMD-Staging by Swirrl.
The boundaries data would be uploaded to PMD-Beta at a later date.

The two Emissions ticket being blocked are removed from this **Update of GeoJson on PMD#70** ticket.
