### ISSUE TITLE
Recreate article measuring-greenhouse-gas-emissions

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#8]
BLOCKED BY SIGN OFF OF UPDATED ARTICLE ON CURRENT PORTAL
Complete updated text for this article is available and is saved in Github repo as issue #451. Use this updated text to create this article on v.2.0 build. Could also unlock v1.1 QA issues raised informally by CC team.

Items to complete:
- [x] Title and introduction
- [x] Measuring UK progress towards net zero section leading to figure 1
- [x] Figure 1: Net greenhouse gas emissions on a territorial basis were down 47% in 2021 compared with 1990 levels. NB static image to dd chart
- [x] Text leading to figure 2
- [x] Figure 2: Actual and temperature adjusted greenhouse gas emissions, UK, 2009 to 2021 (Mt CO2e).  NB static image to dd chart
- [x] Emissions estimates comparable with economic data section leading to figure 3
- [x] Figure 3: Until 2020, households and transport greenhouse gas emissions were relatively stable, while the energy supply sector has trended downwards
- [x] Text leading to figure 4
- [x] Figure 4: The four largest emitting sectors use the most energy from fossil fuels
- [x] Text
- [x] The UK’s carbon footprint section 
- [x] Comparing the three emissions measures section leading to figure 5
- [x] Figure 5: Greenhouse gas emissions on a territorial, residence and carbon footprint basis: UK, 1990 to 2020 and provisional 2021 (Mt CO2e)
- [x] Final text line and footnotes
- [x] Contact details

**Comment by charlesons** [comment]
Issue #140 has been implemented (please see comments in the ticket for details) and will allow authors to control the formatting of axis tick labels. Once the code is deployed the X axis tick label properties for Figure 2 can be updated using Manual mode, `Tick interval` 4, `Max tick label length` 4 and optionally `last label` set as "2021".

Alternatively Auto mode could be selected and the newly provided property `Show n ticks` be set to 14.

There is a minor limitation of the manual mode in that the quarterly X values don't show in the hoverinfo (rollover) text. Reviewed the capability with Bec Williams and Peter French and agreed that this is acceptable for now.

Future ways forward are to:

- Change the date values to actual dates for the dataset that highlighted this issue and Plotly may automatically provide a desirable axis tick label density.
- Explore the tick0 and dtick axis tick label properties in Plotly

**Comment by charlesons** [comment]
The axis tick label formatting implemented by Issue #140 in Chart Builder is now available on the CCv2 staging instance of the CMS. Figure 2 of Measuring Greenhouse Gas Emissions has been updated (as below).

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/fb7122dc-d32b-48c4-b889-93a66ae4a40f)
