### ISSUE TITLE
EPC data update 27 July - Existing Homes

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#89]
The Table EB1: Domestic Energy Performance Certificates for existing dwellings by energy efficiency rating data applies to Mitigation chart 4

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1174160/EB1-_Existing_Domestic_Properties.ods

- [x] Transform data
- [ ]  Review and publish to PMD
- [x]  Update SPARQL query
- [ ]  Vicky/Nile/Amelia update portal content and publish updates

**Comment by osamede20** [comment]
Transform completed and SPARQL query updated
