### ISSUE TITLE
EPC data update 27 July - New Homes

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#94]
Table NB1: Domestic Energy Performance Certificates for new dwellings by energy efficiency rating data applies to Mitigation chart 5
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1174165/NB1-_New_Domestic_Properties.ods

- [x] Transform data
- [ ]  Review and publish to PMD
- [x]  Update SPARQL query
- [ ]  Vicky/Nile/Amelia update portal content and publish updates

**Comment by osamede20** [comment]
Transform completed and SPARQL query updated.
