### ISSUE TITLE
DESNZ Energy Trends 1.2  - latest data 27 Jul 23

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#95]
This data applies to mitigation chat 1 (Energy consumption by fuel type, UK, 1995 to 2021, million tonnes of oil equivalent (Mtoe))  and 3 (Low-carbon energy consumption by fuel type, UK, 1995 to 2021, million tonnes of oil equivalent (Mtoe))

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1173868/ET_1.2_JUL_23.xlsx

- [x] Transform data
- [x]  Review and publish to PMD
- [x]  Update SPARQL query
- [ ]  Vicky/Nile/Amelia update portal content and publish updates

**Comment by osamede20** [comment]
Dataset is published to PMD and the SPARQL query updated.
